
/* ----------------------------------------------------------------------------
 * This file was automatically generated by io-js-autogen Version 0.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify the
 * C header file instead.
 * ----------------------------------------------------------------------------- */

var methods = function(options) {
  var self = this;
  self.io = options.io;
  self.handle = options.handle;
  var map = {};


  /****************************************
             face_detection
  ****************************************/

  map['getDispwndV8'] = function() {
    self.handle.funcReq(self.io.getDispwndV8, 'getDispwndV8');
  };

  map['setDispwndV8'] = function() {
    self.handle.funcReq(self.io.setDispwndV8, 'setDispwndV8');
  };

  map['face_detection'] = function() {
    self.handle.funcReq(self.io.face_detection, arguments, 'face_detection');
  };

  map['face_detection_run'] = function() {
    self.handle.funcReq(self.io.face_detection_run, arguments, 'face_detection_run');
  };

  self.map = map;
};

module.exports =  methods;
