/* ----------------------------------------------------------------------------
 * This file was automatically generated by io-js-autogen Version 0.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify the
 * C header file instead.
 * ----------------------------------------------------------------------------- */
#include "face_detection_addon.h"
#include "stdlib.h"
#include "string.h"
#include "_globalvar.h"

using namespace v8;


// 11: extern int face_detection ( int interval , face_detection_cb_t cb ) ;
Handle<Value> face_detectionV8(const Arguments &args) {
    HandleScope scope;
    
    // Convert V8 parameters to C++
    
    V8_ASSERT(args[0]->IsInt32(), "args[0] parameters error!");
    int arg0 = (int)args[0]->IntegerValue();
    
    
    V8_ASSERT(args[1]->IsFunction(), "args[1] parameters error!");
    cbArray[0] = Persistent<Function>::New(Local<Function>::Cast(args[1]));
    face_detection_cb_t arg1;;
    arg1 = cbFunc0;
    
        
    // Call C++ function
    int ret = (int)face_detection(arg0, arg1);
    
    
    
    // Convert C++ return value to V8
    Handle<Value> retV8 = Int32::New(ret);
    
    return scope.Close(retV8);
    
}
// 12: extern void face_detection_run ( ) ;
Handle<Value> face_detection_runV8(const Arguments &args) {
    HandleScope scope;
        
    // Call C++ function
    face_detection_run();
    
    
    return scope.Close(Undefined());
    
}
static void SetMemberFunc(Handle<Object> obj) {
    obj->Set(v8::String::NewSymbol("face_detection"),
           FunctionTemplate::New(face_detectionV8)->GetFunction());

    obj->Set(v8::String::NewSymbol("face_detection_run"),
           FunctionTemplate::New(face_detection_runV8)->GetFunction());
}


// Const defined by macros
static void SetConst(Handle<Object> obj) {

}

// Const defined by enumeration
static void SetEnumConst(Handle<Object> obj) {

}

// Setter and Getter function for global variable
Handle<Value> GetDispwndV8(const v8::Arguments &args) {
    HandleScope scope;

    Handle<Value> dispWndV8 = Boolean::New(dispWnd);
    
    return scope.Close(dispWndV8);
}

Handle<Value> SetDispwndV8(const v8::Arguments &args) {
    HandleScope scope;

    V8_ASSERT(args[0]->IsBoolean(), "parameter for global var 'dispWnd' error");
    dispWnd = (bool)args[0]->BooleanValue();
    
    return scope.Close(Undefined());
}


static void SetGlobalVarFunc(Handle<Object> obj) {

    obj->Set(v8::String::NewSymbol("getDispwndV8"),
           FunctionTemplate::New(GetDispwndV8)->GetFunction());

    obj->Set(v8::String::NewSymbol("setDispwndV8"),
           FunctionTemplate::New(SetDispwndV8)->GetFunction());
}

void Initface_detection(Handle<Object> exports) {

    SetMemberFunc(exports);

    SetConst(exports);

    SetEnumConst(exports);

    SetGlobalVarFunc(exports);
}
