
(function(exports, global) {

/* ----------------------------------------------------------------------------
 * This file was automatically generated by io-js-autogen Version 0.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify the
 * C header file instead.
 * ----------------------------------------------------------------------------- */

var Board = function(options) {

  submit = options.submit;
  
  var self = this;
  
  self.submit = options.submit;
  
  self.config  = function(options) {
    submit.config(options);
  };
  

/****************************************
           face_detection
****************************************/

  /**
   * @function IO#face_detection
   * @type function  
   * @param {Callback_face_detection_cb_t} cb
   * @param {Integer} interval  
   * @returns {Integer}
   * @instance
   */
  self.face_detection = function() {
    return self.submit.funcReq('face_detection', arguments);
  };

  /**
   * @function IO#face_detection_run
   * @type function  
   * @param {Void}  
   * @returns {Void}
   * @instance
   */
  self.face_detection_run = function() {
    return self.submit.funcReq('face_detection_run', arguments);
  };


/**
 * @callback Callback_face_detection_cb_t
 * @param {Integer}
 * @param {Array}
 * @returns {Void}
 */

}; //end of Board class declare

exports.Board = Board;

})(typeof exports === 'object'? exports: this.IOLIB, this.IOLIB);
