/* ----------------------------------------------------------------------------
 * This file was automatically generated by io-js-autogen Version 0.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify the
 * C header file instead.
 * ----------------------------------------------------------------------------- */
#ifndef _GLOBALVAR_H
#define _GLOBALVAR_H

#include <string.h>
#include <map>
#include <node.h>
#include <v8.h>

using namespace v8;

#ifndef V8_EXCEPTION
#define V8_EXCEPTION(info) { \
    v8::ThrowException(Exception::Error(v8::String::New(info))); \
    }
#endif

#ifndef V8_ASSERT
#define V8_ASSERT(cond, ...) \
    if(!(cond)) {  \
        char buffer[512]; \
        sprintf(buffer, __VA_ARGS__); \
        V8_EXCEPTION(buffer); \
    }
#endif

extern Persistent<Function> cbArray[0];

extern std::map <void *, Persistent<Object> > CClassToJsObjMap;
extern std::map <void *, Persistent<Object> >::iterator iter;
extern Persistent<Object> JSObj;


#endif
