
# ----------------------------------------------------------------------------
# This file was automatically generated by io-js-autogen Version 0.0.1
#
# Do not make changes to this file unless you know what you are doing--modify the
# ext.gypi instead.
# -----------------------------------------------------------------------------


#skeleton of node-gyp file

{
  'targets' : [{

    'target_name' : 'galileo',

    'sources' : [
      'src/face_detection_addon.cpp',
      'src/main.cpp',
      'src/_globalvar.cpp'
      
    ],

    'include_dirs' : [
      'src/',
      '/Users/zliu9/work/face_detection',
      
    ],

    'libraries' : [
       "../../../../face_detection/build/libfd.a /usr/local/lib/libopencv_calib3d.dylib /usr/local/lib/libopencv_core.dylib /usr/local/lib/libopencv_features2d.dylib /usr/local/lib/libopencv_flann.dylib /usr/local/lib/libopencv_highgui.dylib /usr/local/lib/libopencv_imgcodecs.dylib /usr/local/lib/libopencv_imgproc.dylib /usr/local/lib/libopencv_ml.dylib /usr/local/lib/libopencv_objdetect.dylib /usr/local/lib/libopencv_photo.dylib /usr/local/lib/libopencv_shape.dylib /usr/local/lib/libopencv_stitching.dylib /usr/local/lib/libopencv_superres.dylib /usr/local/lib/libopencv_ts.a /usr/local/lib/libopencv_video.dylib /usr/local/lib/libopencv_videoio.dylib /usr/local/lib/libopencv_videostab.dylib"
    ],

    'includes': []

  }]
}
