/* ----------------------------------------------------------------------------
 * This file was automatically generated by io-js-autogen Version 0.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify the
 * C header file instead.
 * ----------------------------------------------------------------------------- */

#ifndef FACE_DETECTION_ADDON_H
#define FACE_DETECTION_ADDON_H

#include <node.h>
#include <v8.h>
#include "face_detection.h"


#endif