/* ----------------------------------------------------------------------------
 * This file was automatically generated by io-js-autogen Version 0.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify the
 * C header file instead.
 * ----------------------------------------------------------------------------- */

#ifndef MAIN_H
#define MAIN_H

#include <node.h>
#include <v8.h>

using namespace v8;

extern void Initgrove_kit(Handle<Object> exports);

#endif
