/* ----------------------------------------------------------------------------
 * This file was automatically generated by io-js-autogen Version 0.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify the
 * C header file instead.
 * ----------------------------------------------------------------------------- */

#include "main.h"

void exportV8(Handle<Object> exports) {

    Initgrove_kit(exports);

}

Handle<Value> IO(const Arguments& args) {

  exportV8(args.This());

  return args.This();
}

void Init(Handle<Object> exports) {
  exports->Set(String::NewSymbol("IO"),
               FunctionTemplate::New(IO)->GetFunction());
}


NODE_MODULE(galileo, Init)
