all:
	make -C atlas_hook
	make -C atlas_nodes
	make -C cpp/cv
	make -C cpp/indoor
	make -C cpp/edirobot

clean:
	make clean -C atlas_hook
	make clean -C atlas_nodes
	make clean -C cpp/cv
	make clean -C cpp/grove
	make clean -C cpp/indoor
	make clean -C cpp/edirobot

.PHONY: all 
