/* ----------------------------------------------------------------------------
 * This file was automatically generated by io-js-autogen Version 0.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify the
 * C header file instead.
 * ----------------------------------------------------------------------------- */

#ifndef GROVE_KIT_ADDON_H
#define GROVE_KIT_ADDON_H

#include <node.h>
#include <v8.h>
#include "grove_kit.h"


#endif